---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autovpa-manager
  labels:
    app.kubernetes.io/name: autovpa
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: autovpa-manager
subjects:
  - kind: ServiceAccount
    name: autovpa
    namespace: autovpa-system
