---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autovpa-leader-election
  labels:
    app.kubernetes.io/name: autovpa
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: autovpa-leader-election
subjects:
  - kind: ServiceAccount
    name: autovpa
    namespace: autovpa-system
