---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: autovpa-metrics-monitor
  namespace: autovpa-system
  labels:
    app.kubernetes.io/name: autovpa
    app.kubernetes.io/component: controller
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      path: /metrics
      port: metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/name: autovpa
      app.kubernetes.io/component: controller
